ALTER TYPE "CategoriaPadel" ADD VALUE IF NOT EXISTS 'TERCERA_CUARTA';
ALTER TYPE "CategoriaPadel" ADD VALUE IF NOT EXISTS 'QUINTA_SEXTA';
ALTER TYPE "CategoriaPadel" ADD VALUE IF NOT EXISTS 'SEXTA_SEPTIMA';
ALTER TYPE "CategoriaPadel" ADD VALUE IF NOT EXISTS 'OCTAVA_NOVENA';
